### ISSUE TITLE
Error in input concept update

### ISSUE THREAD

**Issue by dergus** [darrynten/clarifai-php#34] opened 2017-04-17 18:03 UTC
I'm getting the following error from clarifai while trying to update input concept:
`{"status":{"code":11100,"description":"Bad request format","details":"invalid JSON: %!(EXTRA string=json: cannot unmarshal number into Go value of type string)"}}`,
Here is my code: 
`       $clarifai = sClarifai::getClarifai();
        $concept  = new Concept();
        $concept->setId(self::CONCEPT_BEAUTIFUL)->setValue($this->beautiful == 1)
        $inputResult = $clarifai->getInputRepository()->getById($this->id);
        $modelResult = $clarifai->getInputRepository()->mergeInputConcepts([$this->id => [$concept]]);`

**Comment by vojtik** [comment] 2017-04-17 20:31
Thanks for letting us know! The problem was in integer-to-string unmarshal on the Go side.
The problem is already fixed and merged in master. Pull the master branch, please.
Thank you!

**Comment by dergus** [comment] 2017-04-18 07:04
thanks for quick fix!

**Comment by vojtik** [comment] 2017-04-19 10:22
So, if everything is fine - i'm closing issue. Thanks!

**Closed by vojtik** 2017-04-19 10:22 UTC
